accounts:
  account_1:
    address: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwECVGQ1ZVqyPRfZv2gKC
RCQDN7yz2ciJLl5xsgVI1bP60hykjtecqKWZWr5qO5wjysk+IuaCQstvWt7TAjft
bEvEj8Ci67HKA7tuMYdKSHpFRag1JMX9b7hdK/6gd+bga3TzKY8UgNXX4GQTFGmC
ZFa4ak9hjMjl8t1h1Dj2BggA/dZBd1hVL29a9L4/HaWcPnvN8SGg+RdOarXUtpnv
qOd+DeS3Pld/kwHoFoi9b2vsNXgLD8bQsTqVNBwt5tls13EaMPru9pgdaMh1VhTt
pL/Mw7Br2G6Elcl/dO3sb9M8Omt8aViMcuh5YOKHhjGohajOxfuuUoFYjvg+vckL
cwIDAQAB"
    mnemonic: MNEMONIC_WORDS
    private_key:"MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAQJUZDVlWrI9F
9m/aAoJEJAM3vLPZyIkuXnGyBUjVs/rSHKSO15yopZlavmo7nCPKyT4i5oJCy29a
3tMCN+1sS8SPwKLrscoDu24xh0pIekVFqDUkxf1vuF0r/qB35uBrdPMpjxSA1dfg
ZBMUaYJkVrhqT2GMyOXy3WHUOPYGCAD91kF3WFUvb1r0vj8dpZw+e83xIaD5F05q
tdS2me+o534N5Lc+V3+TAegWiL1va+w1eAsPxtCxOpU0HC3m2WzXcRow+u72mB1o
yHVWFO2kv8zDsGvYboSVyX907exv0zw6a3xpWIxy6Hlg4oeGMaiFqM7F+65SgViO
+D69yQtzAgMBAAECggEAAMN6gOx4JkUUlplzE65LeFwD26gdg/TTcqjMxWe9Xjfs
rzWOg8PtRKnPt55zZPdqsi0yPxVwsmiepLSnQuZLXgQ/bIPxdOn/KU+iKukxWgm+
SUrXPZhzUfFgavXQ1/KsG1Ensn3cF3zoWOUc3EmYMbAHsHubO0g3ymSnTrf6zJOG
yKIWL/EYIvw0fwoK8Ino6TSmqLA/IWUyab4Kx7sYnhqbKD/d5HNxljQvfengVYKE
3fXReeOJh9dlE87vCa8Mgjcb57dwnHq7PJubHh0Uoj0z8p1o0SaAbO4S1s+klCba
LrJKlo3uGU3SZ0FNaoQPMmc7recHaV7DzNjkwrZfIQKBgQDB43Ny5iOitb1MutuS
ivZR9BapyigwI0I+jXEhYn1PE+7uYbKASjgs3oyVf/Df5tY4pcBwVllWTHb+Y8au
IwMgQ/jOfvWjGwbNh+D8idjaq8DHx9QftkMFUFb38dz6wsBRLa15QiI7MAtytfyT
xpgXYLJOhzWp/TXO06R6dTU/4QKBgQD91vLEtFWRDqbctqaasR/AZDMd6uDVzCrQ
McsewFFkfbzNxiLt9kAiXoeFb2I4BwIajV8OLZBGMRsy45lphWYwlQavAHVJk6Id
F6RfmfsE/OTfM174epEEG7+qJUKFf5tLFoEmakSGiEbXYoIoP5MpbIfgZQXUu8wC
fcR3RWYF0wKBgFokKfeAQY8TGXhD43OFAbHmXmb/4qFGszSrw632wTVzmgDgEQIN
/4H00b1rpwwhoPTjMs3Hh29Uy3nH34X0Jy7oCxPN+Nuk5AvIIXSnjddURKNdJyS7
MvuUd2p82vUGeC0FpIIcmheUZa4mJ9B4YxtzTFKwD+YBH/QRd4WrWl9hAoGAOj3g
c+ugmmjPNmMeNO4hB+a1p86liciPpjdWkJa11iXXdStaBlly+6/OznnxAkPxYqA/
SCSCLujDgdig8YovGUSIRQ0I3Dnof15WU60j4FAaP3AtATw2G8g2INbtvW269u6R
8Xt+f5OzFWY/0PZNULrbLkxfmyD/vS6YLnmY4AsCgYEAq8VYbRIWxOuXJNbfFxJO
REPdRAWKZ7XY01uWeYYMeUaM4Am7CGyWTek8w+Iy3bPQP76NNXuMPLKsGp0ezuMk
A4TlrCrvvcFASw2oxpWRfF54sKPDbf4zLlCZsgaIag7YxYsN+bwbVCCdVYK7KZuV
3nUxyC8BftPr58pUYzYLBHk="
  account_2:
    address: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq3yKWltmuLWODGjIZQSQ
HTpdo6UB0OebWIIys/g4LY24QJtuJhaAVRY+XPr71j/XmPplpX7XQLgVDvWH5VWC
viAa1Py1aNHO0w85P7c14LmUw5qOH4tXa/mDJdilW+6uMHq4Ju5Cp0+ezNfoQ7c/
0Wt5lCn62uxsbf+vhGyFvqeU/QgJ7qJrl+SiJ3RwZV0f9V4ZM/Yk4+ENs4+R5p4Q
BdMClif95ts7onitKRWvlPEMM1oFYHqIiXeOC4aKg0XAS9NFbZd48BCbWcNo07VI
NuMz1hGnPAtQtxeKhsnLhxBQCXgcRQR/UarG/zj/uDhn40plBC4hDCxdYQ9bl0Uh
MQIDAQAB"
    mnemonic: MNEMONIC_WORDS
    private_key:"MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCrfIpaW2a4tY4M
aMhlBJAdOl2jpQHQ55tYgjKz+DgtjbhAm24mFoBVFj5c+vvWP9eY+mWlftdAuBUO
9YflVYK+IBrU/LVo0c7TDzk/tzXguZTDmo4fi1dr+YMl2KVb7q4wergm7kKnT57M
1+hDtz/Ra3mUKfra7Gxt/6+EbIW+p5T9CAnuomuX5KIndHBlXR/1Xhkz9iTj4Q2z
j5HmnhAF0wKWJ/3m2zuieK0pFa+U8QwzWgVgeoiJd44LhoqDRcBL00Vtl3jwEJtZ
w2jTtUg24zPWEac8C1C3F4qGycuHEFAJeBxFBH9Rqsb/OP+4OGfjSmUELiEMLF1h
D1uXRSExAgMBAAECggEAAbhNqqAG+wdvIfunDuHawbZxdJnfnGee4tyZlvhZDW78
/FSXrTn22xTYQyAq1zhr7pwp2ZgT2ky0gV1dhhmzYXTw0mozDqp2gAr00JMqrxfv
3huYzmWSYKmNJC9XOxUzN29CbghMV5x6SLhxVk5gb94eAke50MGt0y/+UCCzIXk5
pMHsNjk0u7WG7SE5xETDTAJDPa3Xorc/eMiaOHZ95vMlQk33weKocau1/AVaS0qi
kyet69mzq+10EXlp1v69p9qDyCXgWLDuM5EscGmfJXuvWFLpkpUL8jEHLpMD5LcH
nVT+mCOuGzIrCMgWW9X8XfVvrpioazp0Ky3sSt3eMQKBgQC2ATEzP85xnVrHYD71
WiJRec/3rC0bdsoRHMDdclActtiJnOWeIHlz1IDTAYbOVV91qzmAqj2y16QLwjKH
BT0q5l5dHEF8+U4qdj/QlScCg592FAJYFfBpt/fYFcEhbrLcfncaGdlKdsm2B1Ud
9VDkbemkxGCOWCEEmrzTMHEkzQKBgQDxNKF2qszz9cN1QsK/dSNtkG2tjTxBrnnO
8v4RiqVok3I6NsRISMgcs0Y1olGcXHoP8peiw6BVy0XN5rmh2LP+1JF7CeWYVrr2
jUuwUBaMRdwmXx/qtpiVn/vmfEgV19VPF3v9NAUIagGpcxB3WMZrbEl+LUaaBxSZ
a1xqUJiN9QKBgF4jm7kwZa2qgEvj4myxpFKUOReYPPSZqsbTIoboG7veb34uYy45
Cdj5r3B0t699xRRt7h448BTTKQzT86KW+R55bZGnjdAAe4fHBhbzLuxD/HTswJGj
N2jXOSDRj8WlJmqaFyyu9g9oBclbXZFTU/XzTAhncrHtr5ZcGxL5WWx5AoGBALqo
W/sVGh4Apg1saID5CT2UcwvHLEY32xOHf43bmT1gPRlHoIW/rPxoz4BZ6IX0GpGU
zjuq370E3TQFxMm2hTRDE4H/mqlVFMIPfe8nSwuqVD9thamBPHstnyYyLyaYK/5U
0iKTywFD551V6fwxuvsOhaEbMHOp3wsKxi2PyT6xAoGAUeUpMmlaKlQWLPQ7j3+9
CzawVGttWMOIPecx1kHdS1degdqKEkVSNN0yxqPD+ewRdmLCiXdchRmxaTgFTtNQ
U9RMAQQiXDytOx+zbmehvO6w4Iw6vlWxECb+4DtqipKmMb1hgoyTD084DjZHkEhl
luNCkZP3q1STNYl7OrYITnU="
  account_3:
    address:"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArUpsR8I9XfdBIv1dgWp+
Yii+8uZfH5iMXJCUCzEe2LoTbuk0W93U90VW+00klXTpDRRhPP6Jn6sXiDwDeDY+
oqm2VAWdti1T6HbDykV0tahBKpyA11ya4ic4QXFgyi/HRCKb7g2//uGjYJuOVc19
gybYwUcC3zxjLtsBjT1312eCE8RC0rZzlLexIj3EpI0rcY0Gd6heuYdWFIhjViHJ
IYmch8rtapjfNhRfkI1wODpGRENa3+rbIDrtzHKbS57OCOKcPwa+krNGcIaMfdzZ
DyJjA+fgo4aL8ido3dQZhshIkcsgVVUV91g8qOgjs4CQ38BZeVzxMBd0zdzlNWfH
ZwIDAQAB"
    mnemonic: MNEMONIC_WORDS
    private_key: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtSmxHwj1d90Ei
/V2Ban5iKL7y5l8fmIxckJQLMR7YuhNu6TRb3dT3RVb7TSSVdOkNFGE8/omfqxeI
PAN4Nj6iqbZUBZ22LVPodsPKRXS1qEEqnIDXXJriJzhBcWDKL8dEIpvuDb/+4aNg
m45VzX2DJtjBRwLfPGMu2wGNPXfXZ4ITxELStnOUt7EiPcSkjStxjQZ3qF65h1YU
iGNWIckhiZyHyu1qmN82FF+QjXA4OkZEQ1rf6tsgOu3McptLns4I4pw/Br6Ss0Zw
hox93NkPImMD5+CjhovyJ2jd1BmGyEiRyyBVVRX3WDyo6COzgJDfwFl5XPEwF3TN
3OU1Z8dnAgMBAAECggEACC9dOPB4RJFyrqvn+D5m9Mz24/M0qAHlE1Qy4epyigsT
8uep9PLf5cQNLTaCFVsdzOPbCe394yBKLsGi6lEpmTZJ6eMQBXRTo8XETrAEKLZn
SZN11HZHzInMsu6fgz1JfLLjyZU1rdzLgjsmuG/Jz2GM2Gg5vwCTsLlgc+Lk37Qs
UJ6BfK5jPg3vckua182BCqV6JZNO+4wPO9f5HiqkuN6ZxV8GV6uWqYnUDa3aKtmi
oz4+aPN7SWtexePW9YiGXIz4fU6DkJTJFFYTGTRzOTMVIC99L7zK9Fd179hIUiJ6
2Fd1woSOfw5LywUZjjs+oLjAVsdCheTXU3piW1aitQKBgQC36CGYak8FBawlRTNv
zJh36cWf5Hod6bNGHUfPfYt6NNcmYIMSEZtLyztOYZvPAYdbVSraI6Pc01dpociX
rlrnpM2jGCaeBMMYb1IN3r7e2pmAy7cLPR2ccZpbnYLyYJu07aZZ0lbrryUqZgaO
eLx4Nq8/Siio38kgAFaJPw9WQwKBgQDxOOx3nTgCZBvWmxUSMcgOSC42+fCi6COO
TJUPOVNJ4PfgjNqiBRislthwdDan+ne/EkDZIFqoDTzRLksrPQtXZSvBBDk/b28c
qzmWC0kcmKjx0+gb4jbtVz++s5/+jMfj6r6sTCLXfUTn5HIjMwI3WFxlcIeUGJ5I
3hbEry6iDQKBgQCEL8PGC9OUZolfmKfqGgMVXeCAlvb3fT0wjmdJSpHwWv6yRPix
Chq3lfKg2iPl3NFv4n2Uob1sQjQ4ZuMJs3b/vUNZkUhgmEeqzokKEyragAGJw+Nj
nqAkDLvIUiUHFk2U9KR3N2rmqNNr8D2SNlIxjgzUzvb+uyuTZurMZ5kchQKBgQDo
VGwkdK9qViMd2nY79Oh7IPgqCSbEsJL2TjpO1GasxFnZ07AL1p7CM/M4tCWkOi+1
Pw5oUaofK8jErDLH7V6MCSxQFhJRT7GTyjKHmk0Lltk5OWDX4lQG2j7SHM1fbRZl
JUYKSrZQGB4SvstTraBXz+oF5ZEfiWqCQi1puFRQzQKBgENz3gv7i5o/Sj0E49nY
g+0mDk3lQ43DaA+g7g5GOYkovzjoeUzkPi7i+S0fXxtCoK611aXMT9xSLH/s1zbA
/LYOSBZ0v+OM5TUlmBUvhZ5o6qD57c8WAHPTpTbaZAf6u/h81PmTqTvo3TONbf6s
VAKBk0jfv7Mdm4d2jw9kC03/"
  total: 3

client_credentials:
  db_username = "Jane"
  db_password = "12345qwerty"
